### PR TITLE
Rename pylama.ini to pylava.ini

### PR DESCRIPTION
**Pull request by romanosipenko**
As we use `pylava` instead of `pylama` we have to rename configuration file as well.
Otherwise, `pylava` do not see our settings and uses the default.

### CODE REVIEW

**Comment by alexryabtsev** [comment]
The latest version of [pylama](https://pypi.org/project/pylama/) (_7.7.1_) works with Python 3.6 and 3.7. We've tested it on [gan](https://github.com/django-stars/gan/blob/development/api/pylama.ini).

**Comment by romanosipenko** [comment]
@alexryabtsev yes, I know. I do not have an opinion, what should we use, if there any benefits of using `pylava` or `pylama`, but currently we have "broken" skeleton.

**Comment by alexryabtsev** [comment]
Oh. Now I see: config file has name `pylama.ini` but has contents for `pylava`. I guess instead of renaming it's better to change the contents to `pylama`.

**Comment by romanosipenko** [comment]
@alexryabtsev you can do this :) Also, we have to update Pipfile (where you can suggest to replace it with something else).

The proposed change allows the skeleton to be consistent. We test this and sure, that renaming of the file is minimal and working change.

Changes you propose require "more work", and have to be tested. But I'm lazy.

Also, let's made a review, what `pylava` team think about existance of their fork. They made it because of `pylama` contributors were unresponsive and the fact that they accepted the latest pull requests (with support of 3.7) is not the reason to consider `pylava`  live again and should be in our skeleton again.

**Comment by alexryabtsev** [comment]
> you can do this :)

I will. Maybe next week.

> The proposed change allows the skeleton to be consistent. We test this and sure, that renaming of the file is minimal and working change.

Ok. Got your point.

**Comment by alexryabtsev** [comment]
> @alexryabtsev you can do this :) Also, we have to update Pipfile (where you can suggest to replace it with something else).
> 
> The proposed change allows the skeleton to be consistent. We test this and sure, that renaming of the file is minimal and working change.
> 
> Changes you propose require "more work", and have to be tested. But I'm lazy.
> 
> Also, let's made a review, what `pylava` team think about existance of their fork. They made it because of `pylama` contributors were unresponsive and the fact that they accepted the latest pull requests (with support of 3.7) is not the reason to consider `pylava` live again and should be in our skeleton again.

**Pull request closed without merging**
